export const DEFAULT_ROW_MAX_LABEL_LENGTH_ALLOWED = 15;
export const DEFAULT_COLUMN_MAX_LABEL_LENGTH_ALLOWED = 30;
export const DEFAULT_ROW_LABEL_SLINT_ANGLE = 0;
export const DEFAULT_COLUMN_LABEL_SLINT_ANGLE = 0;
export const DEFAULT_ROW_LABEL_FONT_SIZE = "7px";
export const DEFAULT_COLUMN_LABEL_FONT_SIZE = "7px";

export const LABELS_MARGIN_BUFFER_IN_PX = 20;
export const INTENSITY_LEGEND_LABEL_SIZE_IN_PX = 25;
export const INTENSITY_LEGEND_GRADIENT_SIZE_IN_PX = 20;
export const INTENSITY_LEGEND_SIZE_IN_PX =
  INTENSITY_LEGEND_GRADIENT_SIZE_IN_PX + INTENSITY_LEGEND_LABEL_SIZE_IN_PX;
export const GROUPING_LEGEND_SIZE_IN_PX = 20;
export const INTENSITY_LEGEND_IDENTIFIER = "ehgl-intensity-legend";
export const ROW_GROUPING_LEGEND_IDENTIFIER = "ehgl-row-grouping-legend";
export const COLUMN_GROUPING_LEGEND_IDENTIFIER = "ehgl-column-grouping-legend";

export const DEFAULT_SIZE_LEGEND_SVG_PADDING = 10;
export const DEFAULT_SIZE_LEGEND_CIRCLE_GAP = 10;
export const DEFAULT_SIZE_LEGEND_CIRCLE_TEXT_GAP = 10;

export const DEFAULT_MIN_RADIUS_FOR_DOTPLOT = 3;
export const DEFAULT_MARGIN_BETWEEN_DOTS = 2;

export const DEFAULT_MARGINS = {
  top: "25px",
  bottom: "50px",
  left: "50px",
  right: "10px",
};
