export const DEFAULT_ROW_MAX_LABEL_LENGTH_ALLOWED = 15;
export const DEFAULT_COLUMN_MAX_LABEL_LENGTH_ALLOWED = 30;
export const LABELS_MARGIN_BUFFER_IN_PX = 20;
export const DEFAULT_ROW_LABEL_SLINT_ANGLE = 0;
export const DEFAULT_COLUMN_LABEL_SLINT_ANGLE = 0;
