export const DEFAULT_ROW_MAX_LABEL_LENGTH_ALLOWED = 15;
export const DEFAULT_COLUMN_MAX_LABEL_LENGTH_ALLOWED = 30;
export const DEFAULT_ROW_LABEL_SLINT_ANGLE = 0;
export const DEFAULT_COLUMN_LABEL_SLINT_ANGLE = 0;
export const DEFAULT_ROW_LABEL_FONT_SIZE = "7px";
export const DEFAULT_COLUMN_LABEL_FONT_SIZE = "7px";
export const DEFAULT_VISIBLE_RANGE = [-1, 1];

export const LABELS_MARGIN_BUFFER_IN_PX = 20;
export const INTENSITY_LEGEND_LABEL_SIZE_IN_PX = 25;
export const INTENSITY_LEGEND_GRADIENT_SIZE_IN_PX = 20;
export const INTENSITY_LEGEND_SIZE_IN_PX =
  INTENSITY_LEGEND_GRADIENT_SIZE_IN_PX + INTENSITY_LEGEND_LABEL_SIZE_IN_PX;
export const GROUPING_LEGEND_SIZE_IN_PX = 20;
export const TOOLTIP_IDENTIFIER = "ehgl-tooltip";

export const DEFAULT_SIZE_LEGEND_SVG_PADDING = 10;
export const DEFAULT_SIZE_LEGEND_CIRCLE_GAP = 10;
export const DEFAULT_SIZE_LEGEND_CIRCLE_TEXT_GAP = 10;

export const DEFAULT_MIN_RADIUS_FOR_DOTPLOT = 5;
export const DEFAULT_MARGIN_BETWEEN_DOTS = 5;
